### ISSUE TITLE
LoadError: cannot load such file -- helpers/generic_sftp_fetcher_helper

### ISSUE THREAD

**Issue by joshua-v-jones** [grosser/forking_test_runner#21]
I'm having an issue running the forking_test_runner on a CI platform circleci. I have ensured all versions are correct.
      parallel_tests (>= 1.3.7)
    parallel (1.20.1)
    parallel_tests (3.7.0)
      parallel
      parallel (~> 1.10)
  parallel_tests (>= 3.7.0)

The issue appears to be a missing helper file. 

When I run :

bundle exec forking-test-runner test/ --group 1 --groups 20

bundler: failed to load command: forking-test-runner (/home/circleci/project/vendor/bundle/ruby/2.6.0/bin/forking-test-runner)
LoadError: cannot load such file -- helpers/generic_sftp_fetcher_helper
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /home/circleci/project/test/helpers/generic_sftp_fetcher_csv_based_helper.rb:4:in `<module:GenericSftpFetcherHelperCsvBased>'
  /home/circleci/project/test/helpers/generic_sftp_fetcher_csv_based_helper.rb:3:in `<top (required)>'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /home/circleci/project/test/test_helper.rb:21:in `block in <top (required)>'
  /home/circleci/project/test/test_helper.rb:21:in `each'
  /home/circleci/project/test/test_helper.rb:21:in `<top (required)>'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:220:in `require'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:220:in `load_test_helper'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:192:in `load_test_env'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:44:in `block (3 levels) in cli'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:203:in `reraise_clean_ar_error'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:44:in `block (2 levels) in cli'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:343:in `block in work_direct'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:518:in `with_instrumentation'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:342:in `work_direct'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:279:in `map'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/parallel-1.20.1/lib/parallel.rb:292:in `map_with_index'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:39:in `block in cli'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:92:in `with_lock'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/lib/forking_test_runner.rb:38:in `cli'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/gems/forking_test_runner-1.11.0/bin/forking-test-runner:8:in `<top (required)>'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/bin/forking-test-runner:23:in `load'
  /home/circleci/project/vendor/bundle/ruby/2.6.0/bin/forking-test-runner:23:in `<top (required)>'
  
  Any help you can provide is greatly appreciated.

**Comment by grosser** [comment]
does it work locally but not on CI ?
If yes then I'd say check that the file is where it should be ... and dump the `$LOAD_PATH` before the require to see what is accessible

**Comment by joshua-v-jones** [comment]
Thank you for the quick reply!

It does not work locally either. I will try to dump the load_path to ensure it is available. When running tests normally the require works and also when running on CI. It is only a problem with forking_test_runner.

**Comment by joshua-v-jones** [comment]
Interesting. If I run the test normally: 
ruby -I test test/models/mapping_test.rb 
I see the test directory in the LOAD_PATH. 
When I run with forking_runner:
 forking-test-runner_helper.rb test/helpers/prestashop_paypal_payment_helper.rb
The directory is not in the LOAD_PATH. 
I ensured the RUBY_ENV=test as well.

**Comment by joshua-v-jones** [comment]
After some investigation it does not have the test directory in the LOAD_PATH when running the forking-test-runner command but the path is avaliable when running rails tests commands. That makes me think I'm missing something in a test helper or some configuration. Ideas?

**Comment by grosser** [comment]
yeah, `$LOAD_PATH << "test"` basically or even better use relative requires
the goal is to have `ruby foo_test.rb` work and atm you rely on rails testing modifying the load-path for you
