### ISSUE TITLE
Only appears to be running a subset of entire suite

### ISSUE THREAD

**Issue by JoshToperBmd** [grosser/forking_test_runner#8]
I've got forking_test_runner set up on Travis roughly as described here: https://developer.zendesk.com/blog/big-and-fast-tests-taking-our-travis-build-from-4-hours-to-13-minutes#revised-approach-forking-test-runner

I'm running the specs with the following command:

```
forking-test-runner spec --rspec --group 1 --groups 20 --record-runtime amend
```

...which appears to run only 200 out of 500ish specs.

It's entirely possible I'm misunderstanding what this gem does, but if I'm not then is anyone able to explain this please?

**Comment by grosser** [comment]
you are only running groups 1 ... so only 1/20th of the test (by filesize)
make the group argument dynamic and it should work

... I'll look into updating the blog post too :)

**Comment by JoshToperBmd** [comment]
Ah, thanks. Will try.
